testing_mode = true
client_id = "1053288553834-sr62komo1mbc43100l51jbb6ga41pgp6.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = 'https://cineon.streamlit.app/'
redirect_url = "https://cineon.streamlit.app/"